#!/usr/bin/env bash
#A script that displays numbers from 1 to 20. For specific iterations, it should display additional “bad luck” messages:

i=1
while [ $i -le 20 ]
do
echo "$i"
case $i in
"4") echo "bad luck form china";;
"9") echo "bad luck form japan";;
"17: echo "bad luck from Italy";;
esac
(( i++ ))
done

