#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only isplays te part of the name after the first dash

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
